name:        galois-fft
version:     0.1.0
synopsis:    FFTs over finite fields
description: Finite field polynomial arithmetic based on fast Fourier transforms
maintainer:  Adjoint Inc (info@adjoint.io)
license:     MIT
github:      adjoint-io/galois-fft
category:    Cryptography

default-extensions:
  - LambdaCase
  - OverloadedStrings
  - NoImplicitPrelude

dependencies:
  - base           >= 4.10  && < 5
  - protolude      >= 0.2   && < 0.3
  - vector         >= 0.12  && < 0.13
  - poly           >= 0.5   && < 0.6
  - elliptic-curve >= 0.3   && < 0.4
  - galois-field   >= 1.0   && < 2.0

extra-source-files:
  - README.md
  - ChangeLog.md

ghc-options:
  - -freverse-errors
  - -O2
  - -Wall

library:
  exposed-modules:
    - FFT
  source-dirs:
    - src

tests:
  fft-tests:
    main: Main
    dependencies:
      - galois-fft
      - pairing                 >= 1.0  && <1.1
      - QuickCheck              >= 2.13 && <2.14
      - quickcheck-instances    >= 0.3  && <0.4
      - tasty                   >= 1.2  && <1.3
      - tasty-discover          >= 4.2  && <4.3
      - tasty-hunit             >= 0.10 && <0.11
      - tasty-quickcheck        >= 0.10 && <0.11
    source-dirs:
      - test

benchmarks:
  fft-benchmarks:
    main: Main
    dependencies:
      - galois-fft
      - criterion               >= 1.5 && <1.6
      - pairing                 >= 1.0 && <1.1
    source-dirs:
      - bench
